### PR TITLE
Fix pyo3 0.11

### PR DESCRIPTION
**Pull request by Keats**
Which requires Send.
Go back to a simple reader + shortcuts for files and stdin.

### CODE REVIEW

**Comment by Keats** [comment]
cc @luizirber sorry about removing `niffler`, it just was easier that way :(

**Comment by luizirber** [comment]
> cc @luizirber sorry about removing `niffler`, it just was easier that way :(

No problem =]

**Comment by Keats** [comment]
> I went back to niffler and checked how to solve this, and adding a Send bound to everything seems to solve the problem. I'm trying to think about a situation where a Send bound is not needed, but can't think of one...

Yep that's what I was trying initially but it felt like a huge change to niffler for our specific usecase so I didn't do a PR. This is pretty niche.

**Comment by luizirber** [comment]
I don't think it's so niche, I just read https://fasterthanli.me/articles/getting-in-and-out-of-trouble-with-rust-futures which describes having to do exactly that (going back into a crate and fixing `Send` bounds). It is in an async/future-heavy codebase, tho...

**Pull request merged**
