### PR TITLE
Add faidx

### PR DESCRIPTION
**Pull request by wjwei-handsome**
Hi!

A period of conferences slowed down my code progress.

I have now added an IndexedReader and completed the basic functions including random access regions in plain text fasta file and it's `.fai` file.

TODO:
- some fields should be private or public

Best wishes.

### CODE REVIEW

**Comment by wjwei-handsome** [comment]
code style format done

**Comment by wjwei-handsome** [comment]
Hi! @Keats  

Please let me know if where I need to modify :)

Thanks!

**Comment by Keats** [comment]
Hi @wjwei-handsome 

We talked about this a bit internally but indexed fasta files is not something we use. It would be better to have that as a separate crate that uses needletail and we can expose some internals if needed.

**Comment by wjwei-handsome** [comment]
Understand.

I will just keep my fork for some cases to use `faidx`.

Thanks again for such a cool crate, it really help me a lot.😁

**Pull request closed without merging**
