### PR TITLE
Fix compilation without default features, and add CI job to check it

### PR DESCRIPTION
**Pull request by luizirber**
Hi!

I was trying out adding needletail to a project and using the `wasm32-unknown-unknown` target, but for that I had to disable the `compression` feature (which is also default). I ended up finding an error, and seems like CI wasn't checking for this case, so I also added another job.

Oh: is it OK to add another CI job, for checking compilation for `wasm32-unknown-unknown` target? It is enough to just run `cargo build --target wasm32-unknown-unknown` (and add the target with `rustup`), but I think it gets messier to add to an existing job than to create a new one.

UPDATE: the wasm32 CI job is now in https://github.com/onecodex/needletail/pull/37/commits/07743c8406f9c9028a7dd65bb464072a5a311b7a, but I can remove it from the PR if that's not desirable.

### CODE REVIEW

**Comment by luizirber** [comment]
Ready for review @bovee

**Comment by bovee** [comment]
This is fantastic; super exciting it's this easy to get it run on wasm. Thanks for adding tests on the `not(feature = "compression")` branches too!

**Comment by luizirber** [comment]
Any opposition to release `0.3.2` to crates.io containing these changes? =]

**Comment by bovee** [comment]
Thanks for the reminder; just bumped it.

**Pull request merged**
